version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=usersecurity
      -  MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
